### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by alexcamlo** [bencochran/bezelhud#2] opened 2009-08-31 12:52 UTC
If I activate BezelHUD, Quicksilver will always open at the same Space, instead of opening in any space you are as happened with Bezel o Primer style.
p.e. I active BezelHUD when I'm at Space 2, change to Space 1, press ctrl+space and it shifts to Spaces 2 and opens QS.

**Comment by bencochran** [comment] 2009-09-02 04:53
This appears to be a Quicksilver issue.

see:
http://code.google.com/p/blacktree-quicksilver/issues/detail?id=225
http://code.google.com/p/blacktree-quicksilver/issues/detail?id=232
http://code.google.com/p/blacktree-quicksilver/issues/detail?id=234

This same issue is present with Primer. Bezel, however, is unaffected. This seems to spawn from the fact that Bezel auto-positions itself in the center and doesn't allow itself to be moved.

I'll dig a little more and see if there's a way to fix the bug on my end or if we have to wait for a Quicksilver update.

**Comment by bencochran** [comment] 2009-09-02 16:51
Also a temporary workaround according to http://snowleopard.wikidot.com/ is to check "Snow Icon in Dock"

I've tested on my machine and it does seem to work.

Not ideal, but should make Quicksilver usable until the issue is resolved.

**Comment by ghost** [comment] 2009-09-11 20:03
"This seems to spawn from the fact that Bezel auto-positions itself in the center and doesn't allow itself to be moved."

 It's not specifically because Bezel auto-positions itself at center, while BezelHUD allows the user to position it. Fumo, from Lipidity, allows the user to position it and works fine with Snow Leopard's Spaces.   Maybe you could get Ankur's implementation of this...

**Comment by thewierdone2000** [comment] 2009-09-15 03:21
Could be fixed by setting the following in BHWindow.m, assuming that QSBorderlessWindow extends NSWindow?

[self setCollectionBehavior:  NSWindowCollectionBehaviorMoveToActiveSpace];

As documented in: 

https://developer.apple.com/mac/library/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/Reference/Reference.html#//apple_ref/occ/instm/NSWindow/setCollectionBehavior:

**Comment by bencochran** [comment] 2009-09-15 03:28
Oh wow. Good timing. I was literally reading that documentation when gmail let me know you posted this. (I followed it from here http://twitter.com/chockenberry/status/3986129775)

I'm on my old powerbook tonight while my new laptop is with Apple. But tomorrow I should be getting it back and will recompile with the change and see if it works.

Thanks for the heads up.

**Comment by bencochran** [comment] 2009-09-17 04:26
simple fix to spaces bug. Closed by fb207c3fece93bce1ee234af9a69938a434106c3

**Closed as completed by bencochran** 2009-09-17 04:26 UTC
Labels: bcochran, quicksilver
